- name: Ensure Host Controllers are not using pihole DNS exclusively
  lineinfile: 
    dest: "/etc/resolvconf/resolv.conf.d/head"
    line: '{{ item }}'
  with_items:
    - 'nameserver 192.168.0.1'
    - 'nameserver 8.8.8.8'
    - 'nameserver 1.1.1.1'
  when: OS_VERSION_NUMBER | float < 22.04
- name: Apply DNS service
  tags: dns
  shell: systemctl enable --now resolvconf.service
  when: OS_VERSION_NUMBER | float < 22.04

- name: Ensure Host Controllers are not using pihole DNS exclusively
  lineinfile: 
    dest: "/etc/resolv.conf"
    line: '{{ item }}'
  with_items:
    - 'nameserver 192.168.0.1'
    - 'nameserver 8.8.8.8'
    - 'nameserver 1.1.1.1'
  when: OS_VERSION_NUMBER | float > 22.04

- name: Apply DNS service
  tags: dns
  shell: resolvconf -u
  when: OS_VERSION_NUMBER | float > 22.04

- name: Apply DNS service
  tags: dns
  shell: resolvconf -u
  when: OS_VERSION_NUMBER | float > 22.04

- name: Set Timezone
  shell: timedatectl set-timezone {{TZ}}