---
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/mnt/nginx-lb"
    - "/mnt/nginx-lb/certs"
    - "/opt/templates"

- name: Generate Self Signed Certificate for NGINX
  shell: openssl req -x509 -nodes -days 365 -newkey rsa:4096     -keyout /mnt/nginx-lb/certs/key.key     -out /mnt/nginx-lb/certs/tls.crt     -subj "/CN={{ downstream_hostname_public }}"

- name: Deploy Nginx configuration file
  template:
    src: nginx-conf.j2
    dest: "/mnt/nginx-lb/nginx.conf"
    mode: '0644'

- name: Deploy Docker Compose file
  template:
    src: docker-compose.j2
    dest: "/opt/templates/docker-compose.yml"
    mode: '0644'
  
- name: Deploy Nginx Load Balancer Stack
  shell: docker stack deploy -c /opt/templates/docker-compose.yml loadbalancer

- name: Scale Nginx Load Balancer service
  shell: docker service scale loadbalancer_nginx=1
  notify: Restart Load Balancer