---
# Ansible Common Variables
ssh_user: no
ansible_sudo_pass: no
ssh_cert: ~/.ssh/id_rsa
ssh_port: "22"
TZ: America/Toronto

# Pi-hole Variables
pihole_password: adminpass

# NGINX Load Balancer Variables
downstream_hostname: example.domaine.com
downstream_hostname_public: domaine.com
downstream_hostname_internal: internal
downstream_nodes:
  - 10.10.68.207
  - 10.10.68.208
  - 10.10.68.209

# GlusterFS Variables
glusterfs_packages:
  - glusterfs-server
  - glusterfs-client

gluster_replica_count: 3
glusterfs_nodes:
  - "{{ hostvars['lbserver1']['ansible_host'] }}"
  - "{{ hostvars['lbserver2']['ansible_host'] }}"
  - "{{ hostvars['lbserver3']['ansible_host'] }}"

gluster_volumes_paths:
  - /opt/swarm-volumes/nginx-lb
  - /opt/swarm-volumes/pihole-dns

gluster_volumes:
  - name: nginx-lb
    bricks:
      - "{{ glusterfs_nodes[0] }}:{{ gluster_volumes_paths[0] }}"
      - "{{ glusterfs_nodes[1] }}:{{ gluster_volumes_paths[0] }}"
      - "{{ glusterfs_nodes[2] }}:{{ gluster_volumes_paths[0] }}"
  - name: pihole-dns
    bricks:
      - "{{ glusterfs_nodes[0] }}:{{ gluster_volumes_paths[1] }}"
      - "{{ glusterfs_nodes[1] }}:{{ gluster_volumes_paths[1] }}"
      - "{{ glusterfs_nodes[2] }}:{{ gluster_volumes_paths[1] }}"
